spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/egen?currentSchema=egen_schema``
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: none